name: ESLint Review & Fix
on: push

jobs: 
  run:
    name: Review & Fix with ESLint
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]') && toJSON(github.event.commits.*.message) != '[ESLint] Auto formatting.'"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install ESLint
        run: npm install --no-package-lock --no-save eslint

      - name: Check Code
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: '.'
          filter_mode: file

      - name: Run ESLint
        run: ./node_modules/eslint/bin/eslint.js . --fix

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[ESLint] Auto formatting."
          add: "*.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
