name: ESLint PR
on: pull_request

jobs: 
  run:
    name: Review with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install ESLint
        run: npm install --no-package-lock --no-save eslint
        
      - name: Check Code
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '.'
          fail_on_error: true
          filter_mode: file